-- ختمة القرآن - Supabase database
-- 1) Run this SQL in Supabase > SQL Editor.
-- 2) Create an admin account from Authentication > Users.
-- 3) After creating the admin account, replace ADMIN_EMAIL below and run the last INSERT.

create table if not exists public.participants (
  id bigint generated by default as identity primary key,
  name text not null unique,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.khatma_settings (
  id integer primary key default 1 check (id = 1),
  current_week integer not null default 1,
  current_hizb_1 integer not null default 1,
  current_hizb_2 integer not null default 2,
  updated_at timestamptz not null default now()
);

create table if not exists public.week_completions (
  id bigint generated by default as identity primary key,
  week_number integer not null,
  participant_id bigint not null references public.participants(id) on delete cascade,
  completed boolean not null default true,
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  unique (week_number, participant_id)
);

create table if not exists public.admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  created_at timestamptz not null default now()
);

insert into public.khatma_settings (id)
values (1)
on conflict (id) do nothing;

-- 30 participants
insert into public.participants (name) values
('أنيس عثمان'), ('أحمد'), ('محمد'), ('علي'), ('يوسف'),
('سليم'), ('خالد'), ('عمر'), ('عبد الله'), ('معاذ'),
('إبراهيم'), ('محمود'), ('حمزة'), ('أيمن'), ('وليد'),
('أسامة'), ('زياد'), ('بلال'), ('معين'), ('إسلام'),
('ريان'), ('مالك'), ('سيف'), ('حسن'), ('حسام'),
('رامي'), ('مروان'), ('ياسين'), ('طارق'), ('مصطفى')
on conflict (name) do nothing;

alter table public.participants enable row level security;
alter table public.khatma_settings enable row level security;
alter table public.week_completions enable row level security;
alter table public.admins enable row level security;

-- Public read access for the simple participant page.
drop policy if exists "public read participants" on public.participants;
create policy "public read participants"
on public.participants for select
to anon, authenticated
using (active = true);

drop policy if exists "public read current settings" on public.khatma_settings;
create policy "public read current settings"
on public.khatma_settings for select
to anon, authenticated
using (true);

drop policy if exists "public read current completions" on public.week_completions;
create policy "public read current completions"
on public.week_completions for select
to anon, authenticated
using (
  week_number = (select current_week from public.khatma_settings where id = 1)
);

-- Public participant action. This is intentionally simple for a trusted group.
create or replace function public.mark_my_completion(p_participant_id bigint)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  w integer;
begin
  select current_week into w from public.khatma_settings where id = 1;

  if not exists (
    select 1 from public.participants
    where id = p_participant_id and active = true
  ) then
    raise exception 'Participant not found';
  end if;

  insert into public.week_completions
    (week_number, participant_id, completed, completed_at, updated_at)
  values
    (w, p_participant_id, true, now(), now())
  on conflict (week_number, participant_id)
  do update set
    completed = true,
    completed_at = now(),
    updated_at = now();

  return json_build_object('ok', true, 'week', w);
end;
$$;

grant execute on function public.mark_my_completion(bigint) to anon, authenticated;

-- Admin helper
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select exists (
    select 1 from public.admins
    where user_id = auth.uid()
  );
$$;

-- Admin can update any participant's completion state.
create or replace function public.admin_set_completion(
  p_participant_id bigint,
  p_completed boolean
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  w integer;
begin
  if not public.is_admin() then
    raise exception 'Not authorized';
  end if;

  select current_week into w from public.khatma_settings where id = 1;

  insert into public.week_completions
    (week_number, participant_id, completed, completed_at, updated_at)
  values
    (w, p_participant_id, p_completed,
     case when p_completed then now() else null end, now())
  on conflict (week_number, participant_id)
  do update set
    completed = excluded.completed,
    completed_at = excluded.completed_at,
    updated_at = now();

  return json_build_object('ok', true);
end;
$$;

grant execute on function public.admin_set_completion(bigint, boolean)
to authenticated;

-- Start a new week manually. The admin can do this even if not everyone finished.
create or replace function public.admin_start_next_week(
  p_hizb_1 integer,
  p_hizb_2 integer
)
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  old_week integer;
begin
  if not public.is_admin() then
    raise exception 'Not authorized';
  end if;

  select current_week into old_week
  from public.khatma_settings
  where id = 1;

  update public.khatma_settings
  set current_week = old_week + 1,
      current_hizb_1 = p_hizb_1,
      current_hizb_2 = p_hizb_2,
      updated_at = now()
  where id = 1;

  return json_build_object(
    'ok', true,
    'old_week', old_week,
    'new_week', old_week + 1
  );
end;
$$;

grant execute on function public.admin_start_next_week(integer, integer)
to authenticated;

-- Admin can reset the current week if necessary.
create or replace function public.admin_reset_current_week()
returns json
language plpgsql
security definer
set search_path = public
as $$
declare
  w integer;
begin
  if not public.is_admin() then
    raise exception 'Not authorized';
  end if;

  select current_week into w from public.khatma_settings where id = 1;

  delete from public.week_completions
  where week_number = w;

  return json_build_object('ok', true, 'week', w);
end;
$$;

grant execute on function public.admin_reset_current_week()
to authenticated;

-- IMPORTANT:
-- After creating your admin user in Authentication > Users,
-- run this with YOUR admin email:
--
-- insert into public.admins (user_id, email)
-- select id, email from auth.users
-- where email = 'YOUR-ADMIN-EMAIL@example.com'
-- on conflict (user_id) do nothing;
